# Generated by Django 2.1.5 on 2019-02-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'OC/AC'), (2, 'Dom/Mieszkanie'), (3, 'Podróżne'), (4, 'NNW/Na Życie'), (5, 'Inne')])),
                ('car_brand', models.CharField(blank=True, max_length=50)),
                ('car_model', models.CharField(blank=True, max_length=50)),
                ('car_mileage', models.IntegerField(blank=True, null=True)),
                ('car_discounts', models.IntegerField(blank=True, null=True)),
                ('car_engine_type', models.IntegerField(choices=[(1, 'Diesel'), (2, 'Benzyna'), (3, 'Gaz - LPG'), (5, 'Gaz - CNG'), (4, 'Hybryda'), (6, 'Elektryczny')])),
                ('car_engine_size', models.IntegerField(blank=True, null=True)),
                ('house_size', models.IntegerField(blank=True, null=True)),
                ('house_worth', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='generalcontact',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
