# Generated by Django 2.1.5 on 2019-02-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0002_auto_20190224_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontact',
            name='car_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='car_discounts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='car_engine_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='car_engine_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Diesel'), (2, 'Benzyna'), (3, 'Gaz - LPG'), (5, 'Gaz - CNG'), (4, 'Hybryda'), (6, 'Elektryczny')], null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='car_mileage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='house_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='house_worth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecontact',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
